# environment.yml
name: titanic312
channels: [conda-forge]
dependencies:
  - python=3.12
  - pandas=2.3.*
  - pyarrow=17.*
  - arrow-cpp=17.*
  - vs2015_runtime
  - numpy
  - scikit-learn
  - xgboost
  - polars          # Fast DataFrame library (Windows compatible)
  - jupyterlab
  - jupyter
  # GPU-ready preparation (use these when needed)
  # - cupy-cuda11x    # GPU arrays (Windows compatible)
  # - numba           # JIT compiler with CUDA support
  - ipykernel
  - pip
  - pip:
      - -e .
      # Note: For RAPIDS cuDF with NVIDIA GPU on Windows:
      # 1. Use WSL2 + Ubuntu + CUDA Toolkit
      # 2. Or use conda-forge rapidsai channel in WSL
      # 3. Windows native: stick with pandas for now
