# environment.yml
name: titanic312
channels: [conda-forge]
dependencies:
  - python=3.12
  - pandas=2.3.*
  - pyarrow=17.*
  - arrow-cpp=17.*
  - vs2015_runtime
  - numpy
  - scikit-learn
<<<<<<< HEAD
  - xgboost
=======
  - matplotlib
  - seaborn
  - plotly
  - jupyter
>>>>>>> 17c7a2fcdac9f6a2bb73471d5882bd9e1d3d28cb
  - jupyterlab
  - jupyter
  - ipykernel
  - pip
  - pip:
      - -e .
