# environment.yml
name: titanic312
channels: [conda-forge]
dependencies:
  - python=3.12
  - pandas=2.3.*
  - pyarrow=17.*
  - arrow-cpp=17.*
  - vs2015_runtime
  - numpy
  - scikit-learn
  - xgboost
  - jupyterlab
  - jupyter
  - ipykernel
  - pip
  - pip:
      - -e .
