# environment-wsl-gpu.yaml
# For WSL2 + Ubuntu + NVIDIA GPU setup
name: titanic-gpu
channels:
  - rapidsai
  - conda-forge
  - nvidia
dependencies:
  - python=3.11
  - cudatoolkit=12.4
  - cudf=24.12.*      # Latest RAPIDS cuDF
  - cupy
  - dask-cudf         # Distributed GPU processing
  - cuml              # GPU machine learning
  - pandas=2.3.*
  - pyarrow=17.*
  - numpy
  - scikit-learn
  - xgboost
  - jupyterlab
  - jupyter
  - ipykernel
  - pip
  - pip:
      - -e .

# Usage instructions:
# 1. Install WSL2 + Ubuntu: wsl --install Ubuntu
# 2. Install NVIDIA drivers + CUDA in WSL
# 3. conda env create -f environment-wsl-gpu.yaml
# 4. conda activate titanic-gpu
